Repository spiketools/spiketools, pull requests merged in 2021-11, with the labels that each got.

#76 [BUG] - Issue with `create_spike_train`
  spiketools/measures/conversions.py
Labels: bug, 0.1

#68 [ENH] - Added Test Function for `test_refractory`
  spiketools/sim/utils.py
  spiketools/tests/sim/test_utils.py
Labels: enhancement, 0.1

#82 [ENH] - Updates to plots
  doc/api.rst
  spiketools/plts/annotate.py
  spiketools/plts/data.py
  spiketools/plts/settings.py
  spiketools/plts/space.py
  spiketools/plts/spikes.py
  spiketools/plts/stats.py
  spiketools/plts/trials.py
  spiketools/plts/utils.py
  spiketools/tests/plts/test_annotate.py
  spiketools/tests/plts/test_data.py
  spiketools/tests/plts/test_space.py
  spiketools/tests/plts/test_spikes.py
  spiketools/tests/plts/test_stats.py
  spiketools/tests/plts/test_trials.py
  spiketools/tests/plts/test_utils.py
  spiketools/tests/utils/test_base.py
  spiketools/tests/utils/test_select.py
  spiketools/utils/base.py
  spiketools/utils/select.py
Labels: enhancement, 0.1

#83 [MNT] - Check & Updates Tests
  spiketools/stats/shuffle.py
  spiketools/tests/conftest.py
  spiketools/tests/measures/test_conversions.py
  spiketools/tests/measures/test_measures.py
  spiketools/tests/plts/test_data.py
  spiketools/tests/plts/test_spikes.py
  spiketools/tests/plts/test_stats.py
  spiketools/tests/sim/test_dist.py
  spiketools/tests/sim/test_prob.py
  spiketools/tests/spatial/test_information.py
  spiketools/tests/spatial/test_occupancy.py
  spiketools/tests/spatial/test_utils.py
  spiketools/tests/stats/test_generators.py
  spiketools/tests/stats/test_permutations.py
  spiketools/tests/stats/test_shuffle.py
  spiketools/tests/tsettings.py
  spiketools/tests/utils/test_checks.py
Labels: 0.1, Maintenance

#85 [MNT] - Added examples to `stats/permutations.py`
  spiketools/stats/permutations.py
Labels: documentation, 0.1, Maintenance
