Repository spiketools/spiketools, pull requests merged in 2022-06, with the labels that each got.

#116 [ENH] - Add reset option to restrict_range
  spiketools/tests/utils/test_data.py
  spiketools/utils/data.py
Labels: enhancement, 0.1

#114 [ENH] - Update and extend plotting
  doc/api.rst
  spiketools/plts/__init__.py
  spiketools/plts/annotate.py
  spiketools/plts/data.py
  spiketools/plts/spatial.py
  spiketools/plts/spikes.py
  spiketools/plts/task.py
  spiketools/plts/trials.py
  spiketools/plts/utils.py
  spiketools/stats/shuffle.py
  spiketools/tests/plts/test_annotate.py
  spiketools/tests/plts/test_data.py
  spiketools/tests/plts/test_spikes.py
Labels: 0.1

#119 [DOC] - Update glossary
  doc/glossary.rst
Labels: 0.1

#120 [ENH] - Update Shuffle Circular-Bins
  spiketools/stats/shuffle.py
  spiketools/tests/conftest.py
  spiketools/tests/measures/test_measures.py
Labels: documentation, enhancement, 0.1

#115 [ENH] - Updated tutorials
  spiketools/spatial/occupancy.py
  tutorials/plot_measures.py
  tutorials/plot_sims.py
  tutorials/plot_spatial.py
  tutorials/plot_stats.py
Labels: documentation, enhancement, 0.1
