Repository spiketools/spiketools, pull requests merged in 2022-08, with the labels that each got.

#135 [MNT] - Drop empty examples files
  .gitignore
  doc/conf.py
  doc/contents.rst
  examples/README.txt
  examples/plot_example.py
Labels: 0.1, Maintenance

#132 [DOC]Add doctests
  spiketools/measures/conversions.py
  spiketools/measures/measures.py
  spiketools/measures/trials.py
  spiketools/sim/times.py
  spiketools/sim/train.py
  spiketools/spatial/information.py
  spiketools/spatial/occupancy.py
  spiketools/spatial/place.py
  spiketools/spatial/position.py
  spiketools/spatial/target.py
  spiketools/spatial/utils.py
  spiketools/stats/anova.py
  spiketools/stats/permutations.py
  spiketools/stats/shuffle.py
  spiketools/stats/trials.py
  spiketools/utils/base.py
  spiketools/utils/checks.py
  spiketools/utils/data.py
  spiketools/utils/epoch.py
  spiketools/utils/extract.py
  spiketools/utils/timestamps.py
Labels: documentation, 0.1

#130 [DOC] - Update tutorials for codebase updates
  spiketools/stats/anova.py
  tutorials/plot_measures.py
  tutorials/plot_sims.py
  tutorials/plot_spatial.py
  tutorials/plot_stats.py
Labels: documentation, enhancement, 0.1
